version: 0.2

env:
  variables:
    NEXT_PUBLIC_API_URL: ''
    PORT: 8080
    REPOSITORY_URI: 448256604766.dkr.ecr.us-east-1.amazonaws.com/luchodemo
    IMAGE_TAG: wiicar-front-demo
    AWS_DEFAULT_REGION: eu-west-1

phases:
  install:
    pre_build:
      commands:
        - echo Installing dependency...
        - npm install -g next
        - npm install -g typescript
        - npm install
    build:
      commands:
        - echo Build started on `date`
        - echo Compiling the Node.js code
        - npm run build
artifacts:
  files:
    - .next/**/*
    - package.json
    - next.config.js
    - tsconfig.json
    - .ebextensions/**/*
